### ISSUE TITLE
Installation Red Squiggles

### ISSUE THREAD

**Issue by evanricard** [dotnet/HttpRepl#263]
![image](https://user-images.githubusercontent.com/30779615/67011338-61b13780-f0bd-11e9-942e-a0c36326e841.png)

Hello dotnet, I see in the nuget package history that this recently just left preview so I want to make sure that I'm not the only one experiencing this. Gonna head to 
https://aka.ms/failure-installing-tool right now. Any help would be appreciated, thanks!

![image](https://user-images.githubusercontent.com/30779615/67011672-12b7d200-f0be-11e9-96a6-6d1e27d8357e.png)
Do I just not have the correct version of the runtime? Thanks!

**Comment by tlmii** [comment]
Sorry for not getting back to you earlier on this. Did you have any success since you posted?

Just as an FYI, you don't need to specify the version since we're out of beta now. So you can just do `dotnet tool install -g Microsoft.dotnet-httprepl`

That said, specifying the version shouldn't cause any issues. The error message you're getting makes me wonder about your .net core sdk installs. It should install fine with any 2.1+ version of the sdk. It might be worth posting over at https://github.com/dotnet/cli to see if they have any ideas.

**Comment by bradygaster** [comment]
@evanricard were you ever able to work around this? If so we'd love some feedback on how you got things working and how we could improve the experience. Thanks.

**Comment by tlmii** [comment]
Closing this for now. @evanricard if you're still having problems, feel free to reopen with any new information you have.
