### ISSUE TITLE
Extra space in set base command leads to error

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/HttpRepl#365]
I copied a url from the web, and pasted that into my `set base` command. I accidently copied a leading space in the url which I did not notice. The command is below.

```
set base  https://azuresearch-usnc.nuget.org/query
```

Which resulted in the error `Must specify a server`

An extra space before the url should not impact the command. Other dotnet commands ignore extra spaces between parameters.

![image](https://user-images.githubusercontent.com/1283154/88446963-87156380-cdfc-11ea-8584-fe45ddffb64d.png)

@bradygaster @tlmii

**Comment by tlmii** [comment]
Got a little trigger happy with the Github app and accidentally closed this.

I'll take a look and see if this is an easy fix with our custom parsing we currently have, and if it is, I'll get this in for 3.1. I've run into it before as well, and it's definitely annoying and not always obvious why it failed. If it's not an easy fix, I'll tag this with the other things that will be fixed with the shift to System.CommandLine, which should handle it properly.

**Comment by sayedihashimi** [comment]
Sounds like a good plan. Thanks.
