### ISSUE TITLE
Curly and square brackets not recognized on PowerShell and CMD

### ISSUE THREAD

**Issue by bellons91** [dotnet/HttpRepl#380]
I noticed that while both PowerShell and CMD recognize correctly curly and square brackets, HttpRepl trims that chars.

![curly brackets not recognized](https://user-images.githubusercontent.com/6106586/90485005-424cc600-e137-11ea-8e0c-8bff79308d27.png)

This makes it impossible to perform POST operations with the `-c` flag because the second argument, if it's a JSON, becomes malformed.

In the below image I pasted this string: `{'this': 'is a json', "with":["different", "characters"]}`

![image](https://user-images.githubusercontent.com/6106586/90485361-b6876980-e137-11ea-9eba-4db1bd13a351.png)

As you can see, both single and double quotes are kept, but {, }, [ and ] are removed.

(yes, this is not a valid operation, but it is meant to show how the chars are trimmed)

**Comment by tlmii** [comment]
@bellons91 just to confirm, you're saying this happens when you paste json, but does the same thing happen to you if you type those characters?

**Comment by bellons91** [comment]
Exactly, it happens both by typing and copy-paste.

**Comment by tlmii** [comment]
Interesting. I can't reproduce that in either powershell or cmd, with either copy/paste or typing it. Are you using a non-english keyboard? I'm wondering if it is something similar to #380.

**Comment by bellons91** [comment]
Yes, I'm using an Italian keyboard.

(ps: the issue you linked is this one ;) )

**Comment by tlmii** [comment]
Whoops! Edited, thanks!

**Comment by bellons91** [comment]
Yes, it could be. Plus, here even copy-paste don't work

**Comment by tlmii** [comment]
Any chance you could try out the latest 3.1 preview and see if it works for you? It has the fix for that bug in it. You can upgrade to the preview with:

```console
dotnet tool update microsoft.dotnet-httprepl --version 3.1.0-preview.20380.2 --global
```

you can always downgrade easily afterwards by just uninstalling and reinstalling the release version (though the preview shouldn't cause you any additional issues - just a collection of bug fixes):

```console
dotnet tool uninstall microsoft.dotnet-httprepl --global
dotnet tool install microsoft.dotnet-httprepl --global
```

**Comment by tlmii** [comment]
@bellons91 We released the final version of 3.1 after I sent the last message. Just checking in to see if you had been able to try it and whether or not it fixed the issue for you. 

Since we put the final version out, you just need to run the normal update command to install 3.1 - no need to specify version:

```console
dotnet tool update microsoft.dotnet-httprepl --global
```

**Comment by bellons91** [comment]
Yes, now it works!
![image](https://user-images.githubusercontent.com/6106586/91431347-8a1ecc00-e860-11ea-9e3e-26cc8104ef80.png)

**Comment by tlmii** [comment]
Great! Glad you're unblocked now.
