### ISSUE TITLE
listing directory yields no results

### ISSUE THREAD

**Issue by clstr** [dotnet/HttpRepl#453]
I am using TrueNas on a fresh install on a vm. I can get to the SwaggerUI via the browser, and the only url near the top i see on that page is http://192.168.56.101/api/v2.0/
![image](https://user-images.githubusercontent.com/1195526/101148287-72877a00-35eb-11eb-9f24-b150c20d8325.png)

which gives the swagger.json it looks like.
![image](https://user-images.githubusercontent.com/1195526/101147991-1e7c9580-35eb-11eb-9ccb-2e47ea5b6869.png)

```
❯ httprepl http://192.168.56.101 --openapi /api/v2
(Disconnected)> connect http://192.168.56.101 --openapi /api/v2
Checking http://192.168.56.101/api/v2... Found
Parsing... Successful (with warnings)
(Lin: 38, Col: 86, Chr: 2765) - (Lin: 38, Col: 86, Chr: 2765): Mapping values are not allowed in this context. [#line=38]

Using a base address of http://192.168.56.101/
Using OpenAPI description at http://192.168.56.101/api/v2
For detailed tool info, see https://aka.ms/http-repl-doc

http://192.168.56.101/> ls
.   []

http://192.168.56.101/>
```

I tried just connecting via httprepl various different ways, but httprepl doesn't find them, the only way it finds it is the example above.

**Comment by tlmii** [comment]
@clstr I'll see if I am repro this in a little bit, but for now, can you try adding `--base /api/v2` to your initial command arguments? It looks on first glance like the swagger file isn't providing a base address and so we just take the root value specified as the base and that's not right.

**Comment by clstr** [comment]
@tlmii 

That appears to list them now, but some endpoints have no listings, like "auth". In the UI view there is "auth" and "auth.twofactor" as separate dropdowns.


![image](https://user-images.githubusercontent.com/1195526/101202461-4bef3080-3637-11eb-83e2-1ae2d0df9d70.png)


```
❯ httprepl http://192.168.56.101 --base /api/v2.0 --openapi /api/v2.0
(Disconnected)> connect http://192.168.56.101 --base /api/v2.0 --openapi /api/v2.0
Checking http://192.168.56.101/api/v2.0... Found
Parsing... Successful (with warnings)
Data and type mismatch found. [#/components/schemas/vm_clone_1/default]

Using a base address of http://192.168.56.101/api/v2.0/
Using OpenAPI description at http://192.168.56.101/api/v2.0
For detailed tool info, see https://aka.ms/http-repl-doc

http://192.168.56.101/api/v2.0/> ls
.                      []
core                   []
acme                   []
activedirectory        [GET|PUT]
afp                    [GET|PUT]
alert                  []
alertclasses           [GET|PUT]
alertservice           [GET|POST]
api_key                [GET|POST]
auth                   []
...
```


Here is their openapi json file
https://gist.github.com/clstr/e58a492fc84fa3e72133afe02f4203b3

**Comment by tlmii** [comment]
@clstr As far as I can tell, this is working as designed. When you do the `ls` command, the tool displays everything that is "inside" the current route. `core`, `acme`, ... , `auth` are all there. The `/auth` route itself doesn't have any operations on it. That's why there's no `GET` or `PUT` or `POST` in the `[]` of the directory listing. If you `cd` into auth and then do an `ls` you'll see the routes that are inside of it.

From your screenshot you can see that all of the routes in the `auth.twofactor` grouping are under `auth` - `/auth/twofactor`, `/auth/twofactor/provisioning_uri`, etc.

I think the `auth.twofactor` grouping is coming from the `tags` section of the swagger document ([spec](http://spec.openapis.org/oas/v3.0.3#operation-object)):

> A list of tags for API documentation control. Tags can be used for logical grouping of operations by resources or any other qualifier.

At the moment, HttpRepl does not support displaying those groups the way the UI tool you're seeing does. I've added #454 to track that.

**Comment by tlmii** [comment]
With #454 tracking the possibility of making use of tags, I'm going to go ahead and close this. @clstr, let me know if you have anything further to address here and we can reopen to discuss.
