### ISSUE TITLE
Split HelpCommand output

### ISSUE THREAD

**Issue by tlmii** [dotnet/HttpRepl#70]
Currently, the HelpCommand has three main code paths when executed:

1. If you just say `help`, it displays a canned and curated lists of commands and their help summaries
2. If you say `help <command> [<subCommand>]`, where <command> is whatever command you're interested in and <subCommand> is an optional subCommand for the command, then you'll get the detailed help for that command (assuming it exists).
3. If you say `help <relativeUrl>`, where <relativeUrl> is a path to a known api endpoint, it displays a more verbose version of what you would have gotten if you (starting at the root) did `cd <relativeUrl>` followed by `ls`. Note that this relativeUrl is always relative to the root, not to the current directory.

For this issue I'm proposing splitting off that third option since it seems to be in the wrong place, and instead making an optional subcommand or argument on the `ls` command, something like `ls verbose` that displays the information in the same format as the current help implementation does, but following the semantics of the current `ls` command where it looks at the current directory.

Not saying this needs to be done now, Just wanted to put an issue out there to track it.

cc @jimmylewis @bhsubra @jodavis for your thoughts.

**Comment by jimmylewis** [comment]
I like the idea of splitting it out.  From a UX perspective, usage 1 and 2 are similar affordances and 3 is quite different.

I'm not sure about the `ls verbose` - right now the ListCommand follows the command line experience.  For example the recursive option follows GNU conventions: `ls -r` or `ls --recursive`.  We could do `ls --verbose` but that doesn't match any existing shell commands.  In Bash, the verbose option is `ls -l` (for long form); I don't see a similar option for `dir` in a Windows command prompt, since it seems fairly verbose by default (though some flags can add specific other metadata).

Worth some further thought, but I'm in favor of the split.

**Comment by tlmii** [comment]
The actual output here is an interesting combination of something like `ls -l`, since it provides more information and `ls -h` since it provides some of the same information in a more human readable form.  Probably not a bad idea to have further discussion about the content of the output before we settle on the command anyway.

**Comment by tlmii** [comment]
Since we settled on `--verbose` (or `-v`) for the connect command, I'm going to bring this back up and say we use the same here.

I'd really like to clean up the help command in anticipation of the System.CommandLine work, and getting this chunk out will go a long way.
